# Default values for nash-pisharp-app on AWS EKS
# This is a YAML-formatted file

replicaCount: 1

image:
  registry: "" # Will be set by Jenkins from ECR registry
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

# Frontend configuration
frontend:
  enabled: true
  name: frontend
  image:
    repository: frontend
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Backend configuration
backend:
  enabled: true
  name: backend
  image:
    repository: backend
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "3000"
    - name: MONGODB_URI
      value: "mongodb://nash-pisharp-app-mongodb:27017/todoapp"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Ingress configuration for AWS ALB
ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    # Optional: Enable HTTPS if you have certificates
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:region:account:certificate/certificate-id
  hosts:
    - host: ""  # Use default host (ALB DNS name)
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 3000
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 3000
  tls: []

# MongoDB configuration
mongodb:
  enabled: true  # Enable MongoDB for the application
  external: false   # Use internal MongoDB
  image:
    tag: "latest"
  auth:
    enabled: false  # Disable auth for simplicity
    rootUser: "root"
    rootPassword: "password"
    database: "todoapp"
  persistence:
    enabled: true  # Enable persistence for AWS
    size: 8Gi
    storageClass: "gp2"  # AWS EBS GP2 storage class
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 27017

# Storage class configuration for AWS EBS
storageClass:
  enabled: true
  name: "nash-pisharp-gp2"
  provisioner: "kubernetes.io/aws-ebs"
  parameters:
    type: "gp2"
    encrypted: "true"
  reclaimPolicy: Retain
  allowVolumeExpansion: true

# Monitoring and observability
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# AWS-specific configurations
aws:
  region: us-east-1
  loadBalancerController:
    enabled: true