# Common policies and configurations

# Pod Security Standards
apiVersion: v1
kind: Namespace
metadata:
  name: nash-pisharp-demo
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Network Policy - Allow only necessary traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nash-pisharp-network-policy
  namespace: nash-pisharp-demo
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: nash-pisharp-demo
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: nash-pisharp-demo
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80

---
# Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nash-pisharp-quota
  namespace: nash-pisharp-demo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "3"

---
# Limit Range
apiVersion: v1
kind: LimitRange
metadata:
  name: nash-pisharp-limits
  namespace: nash-pisharp-demo
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
